### ISSUE TITLE
AWS Well Architected Framework - Reliability Pillar

### ISSUE THREAD

**Issue by vishalgoyal16444** [turbot/steampipe-mod-aws-well-architected#24]
I was reading through this AWS documentation which has following 13 rules provided https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html

•	REL01 - Manage service quotas and constraints
•	REL02 - Plan your network topology
•	REL03 - Design your workload service architecture
•	REL04 - Design interactions in a distributed system to prevent failures
•	REL05 - Design interactions in a distributed system to mitigate or withstand failures
•	REL06 - Monitor workload resources
•	REL07 - Design your workload to adapt to changes in demand
•	REL08 - Implement change
•	REL09 - Back up data
•	REL10 - Use fault isolation to protect your workload
•	REL11 - Design your workload to withstand component failures
•	REL12 - Test reliability
•	REL13 - Plan for Disaster Recovery (DR)

If i look at steampipe documentation, it has following covered. Few of the above ones are related to design which steampipe may not address, but REL10, REL11 look relevant for steampipe to cover is my view. Wanted to check how do we ensure good coverage for each of the WAF pillars in steampipe ?

•	REL01 How do you manage service quotas and constraints?
•	REL02 How do you plan your network topology?
•	REL06 How do you monitor workload resources?
•	REL07 How do you design your workload to adapt to changes in demand?
•	REL08 How do you implement change?
•	REL09 How do you back up data?

**Comment by karanpopat** [comment]
Hey @vishalgoyal16444, welcome to Steampipe! 
Thanks for your interest in the Well-Architected Mod. We're actively working on adding more rules to the list soon. We'll definitely keep you in the loop regarding any updates.

In the meantime, we'd love to hear your thoughts on how you feel about the current coverage. Feel free to share your feedback!

**Comment by vishalgoyal16444** [comment]
Thank you for quick response. We want to leverage steampipe for doing real customer related work and want to ensure customers see value for which it is important to note what is the coverage it offers compared to rules from hyper scalers.

Regards,
Vishal
________________________________

**Comment by cbruno10** [comment]
Hi @vishalgoyal16444 , thanks for checking out the mod and raising this issue!

Our current approach for this mod is to lay the benchmark foundations and then add some mappings based off of our [AWS Compliance mod queries](https://hub.steampipe.io/mods/turbot/aws_compliance/queries), as we we can just reference them in this mod easily. For additional coverage, our plan is to add them over time, but we'd really like community feedback based on checks they run today, how they ensure they're meeting best practices in each pillar, and if they use any existing mappings today that we can also use reference.

Do you run any checks today for the Reliability pillar questions and best practices today? If so, are you able to share what those checks are? Also, do you see any of those already being done in [AWS Compliance mod queries](https://hub.steampipe.io/mods/turbot/aws_compliance/queries)?

If you have any direct suggestions for new question and best practice mappings to existing queries, or you'd like to add new queries to this mod, we are also open to receiving PRs!

**Comment by bigdatasourav** [comment]
Hey @vishalgoyal16444, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
