### ISSUE TITLE
Include AWS Thrifty Controls into Well-Architected Mod for Cost Optimization Pillar 

### ISSUE THREAD

**Issue by JeffreyFudge** [turbot/steampipe-mod-aws-well-architected#39]
The AWS Well-Architected Mod currently covers the Operational Excellence, Security and Reliability pillars.  The AWS Thrifty mod does a great job of identifying cost optimization opportunities, and it seems logical to include these within the Well-Architected mod to provide coverage for the Cost Optimization pillar of the framework.

**Comment by khushboo9024** [comment]
@JeffreyFudge Thanks for raising this issue. We are actively looking into it, and we will keep you informed about any developments.

**Comment by khushboo9024** [comment]
@JeffreyFudge We have some upcoming updates planned for the AWS Thrifty mod controls, but we don't have specific dates yet. As a result, we are not planning to add this in the near future.

As a alternative you can create a customised mod as per your requirement by mixing AWS Thrifty and AWS Well-Architected mods. For guidance on how to implement this, please refer to this [blog]( https://steampipe.io/blog/remixing-dashboards).

Please let us know if you have any other concerns. Thanks.

**Comment by JeffreyFudge** [comment]
Thanks for the update.  I did create a customized mod, but thought it would be helpful (at some point) to have it integrated for everyone’s benefit – sounds like that will likely happen at some point in the future, which is great.

Out of curiosity, do the planned changes ever get shared to the community prior to implementation?

-Jeff

From: Khushboo ***@***.***>
Date: Monday, January 8, 2024 at 12:08 PM
To: turbot/steampipe-mod-aws-well-architected ***@***.***>
Cc: Jeff Fudge ***@***.***>, Mention ***@***.***>
Subject: Re: [turbot/steampipe-mod-aws-well-architected] Include AWS Thrifty Controls into Well-Architected Mod for Cost Optimization Pillar (Issue #39)

@JeffreyFudge<https://github.com/JeffreyFudge> We have some upcoming updates planned for the AWS Thrifty mod controls, but we don't have specific dates yet. As a result, we are not planning to add this in the near future.

As a alternative you can create a customised mod as per your requirement by mixing AWS Thrifty and AWS Well-Architected mods. For guidance on how to implement this, please refer to this blog<https://steampipe.io/blog/remixing-dashboards>.

Please let us know if you have any other concerns. Thanks.

**Comment by khushboo9024** [comment]
@JeffreyFudge We maintain a public repository where we consistently share all ongoing development work with the community. Typically, the community itself initiates most of this development. While we generally create an issue before starting any development, there are occasions where this may not be the case.
