### ISSUE TITLE
Error: Reattachment process not found

### ISSUE THREAD

**Issue by semeiner** [turbot/steampipe-mod-aws-well-architected#47]
**Describe the bug**
Hello, 
I hope the bug report is correctly in this project. If not, please let me know where to address it. 
We are using Steampipe and Powerpipe in our company to execute the Well-Architected-Benchmark. 
For that, we are running multiple containers at the same time to execute the benchmarks in parallel. (using the latest turbot/steampipe image) 
By running multiple container at the same time, some containers are exiting with the error: "Error: Reattachment process not found"
But we can't exactly reproduce the error. Sometimes the container crashes and sometimes it works. 

When we are running different benchmarks like cis v1.5 or the SecurityFoundation-benchmark with Steampipe this error doesn't occur. 

**Powerpipe version (`powerpipe -v`)**
Example: v0.1.3

**Steampipe version (`steampipe -v`)**
Example: v0.22.0

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/aws@latest | 0.136.1 | aws
hub.steampipe.io/plugins/turbot/steampipe@latest | 0.10.0 | steampipe

**To reproduce**
We are running the following command in the container and then the error occurs. 

`powerpipe benchmark run aws_well_architected.benchmark.well_architected_framework --export wafr_${ACCOUNT_NAME}_${DATE}.csv --progress=false >/dev/null 2>&1`

**Expected behavior**
We expect that the benchmark will be done and that the result will be saved in the container. 

**Additional context**
The container is running on fargate, aws.

**Comment by khushboo9024** [comment]
Hi @semeiner,
Sorry for the radio silence on this issue. Could you please try with the latest versions of Steampipe (0.23.3), Powerpipe (v0.4.0), and the AWS plugin (0.144.0) and let us know?
Thanks.

**Comment by misraved** [comment]
Hi @semeiner,

I hope all is well with you. I'm writing to follow up on this issue. Since we haven't received any updates or feedback from you in a while, we'll be closing this issue for now.

If you still need assistance or if you have any further questions, please feel free to reopen the issue or create a new one. We're always here to help!

Thank you for your understanding.
