### ISSUE TITLE
Question maps outdated since June 2024 Well Architected update

### ISSUE THREAD

**Issue by nathanwebsterdotme** [turbot/steampipe-mod-aws-well-architected#48]
**Describe the bug**
Since the June 2024 update to the Well Architected framework, some of the question mappings are now incorrect.  For example, OPS04.BP01 is now focused on KPIs, 
https://docs.aws.amazon.com/wellarchitected/latest/framework/ops_observability_identify_kpis.html

where as the mod is still checking for telemetry:
https://github.com/turbot/steampipe-mod-aws-well-architected/blob/ea7437d94c609fb8847fa9a25b76099a5d03887e/well_architected_framework/operational_excellence/ops04.sp#L18-L37

**Expected behavior**
A review of the mod and best practice mappings is likely needed to bring it up to date across all pillars.

**Comment by khushboo9024** [comment]
@nathanwebsterdotme Thanks for raising this issue. We will update the mod as per the latest documentation as soon as possible.

**Comment by khushboo9024** [comment]
Hi @nathanwebsterdotme

Thank you for raising this issue. We have checked our documentation and confirmed that we strictly adhere to the AWS Audit Manager for well-architected benchmarks.

As per our current process, our benchmark is in sync with the Audit Manager framework. Please find the screenshots below.

Note: The AWS Audit Manager Well-Architected Framework was last updated on May 29, 2024, at 19:59 (UTC+0:00). We will revisit this matter once the framework is updated.

For now, we are closing the issue and reopen it once the latest version comes out.

Thank you for your understanding.

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/21309c3f-69d7-4f9c-832a-fb2262607415">
